const pkmn = [];

function pokemon(name, image) {
    this.name = name;
    this.image = image;
    return this;
}

pkmn.push(new pokemon('bulbasaur', 'images/bulbasaur.png'));
pkmn.push(new pokemon('absol', 'images/absol.png'));
pkmn.push(new pokemon('blissey', 'images/blissey.png'));
pkmn.push(new pokemon('butterfree', 'images/butterfree.png'));
pkmn.push(new pokemon('dragonair', 'images/dragonair.png'));
pkmn.push(new pokemon('dragonite', 'images/dragonite.png'));
pkmn.push(new pokemon('herdier', 'images/herdier.png'));
pkmn.push(new pokemon('hoopa', 'images/hoopa.png'));
pkmn.push(new pokemon('kecleon', 'images/kecleon.png'));
pkmn.push(new pokemon('krokorok', 'images/krokorok.png'));
pkmn.push(new pokemon('lapras', 'images/lapras.png'));
pkmn.push(new pokemon('meowth', 'images/meowth.png'));
pkmn.push(new pokemon('minccino', 'images/minccino.png'));
pkmn.push(new pokemon('mudkip', 'images/mudkip.png'));
pkmn.push(new pokemon('persian', 'images/persian.png'));
pkmn.push(new pokemon('phanpy', 'images/phanpy.png'));
pkmn.push(new pokemon('sandshrew', 'images/sandshrew.png'));
pkmn.push(new pokemon('skitty', 'images/skitty.png'));
pkmn.push(new pokemon('sneasel', 'images/sneasel.png'));
pkmn.push(new pokemon('vaporeon', 'images/vaporeon.png'));
pkmn.push(new pokemon('victini', 'images/victini.png'));
pkmn.push(new pokemon('zapdos', 'images/zapdos.png'));
pkmn.push(new pokemon('shinx', 'images/shinx.png'));
pkmn.push(new pokemon('venusaur', 'images/venusaur.png'));
pkmn.push(new pokemon('charizard', 'images/charizard.png'));
pkmn.push(new pokemon('totodile', 'images/totodile.png'));
pkmn.push(new pokemon('popplio', 'images/popplio.png'));
pkmn.push(new pokemon('raticate', 'images/raticate.png'));
pkmn.push(new pokemon('jolteon', 'images/jolteon.png'));
pkmn.push(new pokemon('psyduck', 'images/psyduck.png'));
pkmn.push(new pokemon('jirachi', 'images/jirachi.png'));
pkmn.push(new pokemon('malamar', 'images/malamar.png'));
pkmn.push(new pokemon('emboar', 'images/emboar.png'));
pkmn.push(new pokemon('articuno', 'images/articuno.png'));
pkmn.push(new pokemon('armaldo', 'images/armaldo.png'));
pkmn.push(new pokemon('munchlax', 'images/munchlax.png'));
pkmn.push(new pokemon('lugia', 'images/lugia.png'));
pkmn.push(new pokemon('marill', 'images/marill.png'));
pkmn.push(new pokemon('caterpie', 'images/caterpie.png'));
pkmn.push(new pokemon('pachirisu', 'images/pachirisu.png'));
pkmn.push(new pokemon('chimchar', 'images/chimchar.png'));
pkmn.push(new pokemon('turtwig', 'images/turtwig.png'));
pkmn.push(new pokemon('sandslash', 'images/sandslash.png'));
pkmn.push(new pokemon('torchic', 'images/torchic.png'));
pkmn.push(new pokemon('azumarill', 'images/azumarill.png'));
pkmn.push(new pokemon('haunter', 'images/haunter.png'));
pkmn.push(new pokemon('vulpix', 'images/vulpix.png'));
pkmn.push(new pokemon('zekrom', 'images/zekrom.png'));
pkmn.push(new pokemon('groudon', 'images/groudon.png'));
pkmn.push(new pokemon('ampharos', 'images/ampharos.png'));
pkmn.push(new pokemon('volcarona', 'images/volcarona.png'));
pkmn.push(new pokemon('togepi', 'images/togepi.png'));
pkmn.push(new pokemon('entei', 'images/entei.png'));
pkmn.push(new pokemon('raikou', 'images/raikou.png'));
pkmn.push(new pokemon('suicune', 'images/suicune.png'));
pkmn.push(new pokemon('pikachu', 'images/pikachu.png'));
pkmn.push(new pokemon('mewtwo', 'images/mewtwo.png'));
pkmn.push(new pokemon('furret', 'images/furret.png'));
pkmn.push(new pokemon('cradily', 'images/cradily.png'));
pkmn.push(new pokemon('lucario', 'images/lucario.png'));

