const pkmn = [];

function pokemon(name, image, cry) {
    this.name = name;
    this.image = image;
    this.cry = cry;
    return this;
}

pkmn.push(new pokemon('bulbasaur', 'images/bulbasaur.png', 'cries/001 - Bulbasaur.wav'));
pkmn.push(new pokemon('absol', 'images/absol.png', 'cries/359 - Absol.wav'));
pkmn.push(new pokemon('blissey', 'images/blissey.png', 'cries/242 - Blissey.wav'));
pkmn.push(new pokemon('butterfree', 'images/butterfree.png', 'cries/012 - Butterfree.wav'));
pkmn.push(new pokemon('dragonair', 'images/dragonair.png', 'cries/148 - Dragonair.wav'));
pkmn.push(new pokemon('dragonite', 'images/dragonite.png', 'cries/149 - Dragonite.wav'));
pkmn.push(new pokemon('herdier', 'images/herdier.png', 'cries/507 - Herdier.wav'));
pkmn.push(new pokemon('hoopa', 'images/hoopa.png', 'cries/720 - Hoopa.wav'));
pkmn.push(new pokemon('kecleon', 'images/kecleon.png', 'cries/352 - Kecleon.wav'));
pkmn.push(new pokemon('krokorok', 'images/krokorok.png', 'cries/552 - Krokorok.wav'));
pkmn.push(new pokemon('lapras', 'images/lapras.png', 'cries/131 - Lapras.wav'));
pkmn.push(new pokemon('meowth', 'images/meowth.png', 'cries/052 - Meowth.wav'));
pkmn.push(new pokemon('minccino', 'images/minccino.png', 'cries/572 - Minccino.wav'));
pkmn.push(new pokemon('mudkip', 'images/mudkip.png', 'cries/258 - Mudkip.wav'));
pkmn.push(new pokemon('persian', 'images/persian.png', 'cries/053 - Persian.wav'));
pkmn.push(new pokemon('phanpy', 'images/phanpy.png', 'cries/231 - Phanpy.wav'));
pkmn.push(new pokemon('sandshrew', 'images/sandshrew.png', 'cries/027 - Sandshrew.wav'));
pkmn.push(new pokemon('skitty', 'images/skitty.png', 'cries/300 - Skitty.wav'));
pkmn.push(new pokemon('sneasel', 'images/sneasel.png', 'cries/215 - Sneasel.wav'));
pkmn.push(new pokemon('vaporeon', 'images/vaporeon.png', 'cries/134 - Vaporeon.wav'));
pkmn.push(new pokemon('victini', 'images/victini.png', 'cries/494 - Victini.wav'));
pkmn.push(new pokemon('zapdos', 'images/zapdos.png', 'cries/145 - Zapdos.wav'));
pkmn.push(new pokemon('shinx', 'images/shinx.png', 'cries/403 - Shinx.wav'));
pkmn.push(new pokemon('venusaur', 'images/venusaur.png', 'cries/003 - Venusaur.wav'));
pkmn.push(new pokemon('charizard', 'images/charizard.png', 'cries/006 - Charizard.wav'));
pkmn.push(new pokemon('totodile', 'images/totodile.png', 'cries/158 - Totodile.wav'));
pkmn.push(new pokemon('popplio', 'images/popplio.png', 'cries/728 - Popplio.wav'));
pkmn.push(new pokemon('raticate', 'images/raticate.png', 'cries/020 - Raticate.wav'));
pkmn.push(new pokemon('jolteon', 'images/jolteon.png', 'cries/135 - Jolteon.wav'));
pkmn.push(new pokemon('psyduck', 'images/psyduck.png', 'cries/054 - Psyduck.wav'));
pkmn.push(new pokemon('jirachi', 'images/jirachi.png', 'cries/385 - Jirachi.wav'));
pkmn.push(new pokemon('malamar', 'images/malamar.png', 'cries/687 - Malamar.wav'));
pkmn.push(new pokemon('emboar', 'images/emboar.png', 'cries/500 - Emboar.wav'));
pkmn.push(new pokemon('articuno', 'images/articuno.png', 'cries/144 - Articuno.wav'));
pkmn.push(new pokemon('armaldo', 'images/armaldo.png', 'cries/348 - Armaldo.wav'));
pkmn.push(new pokemon('munchlax', 'images/munchlax.png', 'cries/446 - Munchlax.wav'));
pkmn.push(new pokemon('lugia', 'images/lugia.png', 'cries/249 - Lugia.wav'));
pkmn.push(new pokemon('marill', 'images/marill.png', 'cries/183 - Marill.wav'));
pkmn.push(new pokemon('caterpie', 'images/caterpie.png', 'cries/010 - Caterpie.wav'));
pkmn.push(new pokemon('pachirisu', 'images/pachirisu.png', 'cries/417 - Pachirisu.wav'));
pkmn.push(new pokemon('chimchar', 'images/chimchar.png', 'cries/390 - Chimchar.wav'));
pkmn.push(new pokemon('turtwig', 'images/turtwig.png', 'cries/387 - Turtwig.wav'));
pkmn.push(new pokemon('sandslash', 'images/sandslash.png', 'cries/028 - Sandslash.wav'));
pkmn.push(new pokemon('torchic', 'images/torchic.png', 'cries/255 - Torchic.wav'));
pkmn.push(new pokemon('azumarill', 'images/azumarill.png', 'cries/184 - Azumarill.wav'));
pkmn.push(new pokemon('haunter', 'images/haunter.png', 'cries/093 - Haunter.wav'));
pkmn.push(new pokemon('vulpix', 'images/vulpix.png', 'cries/037 - Vulpix.wav'));
pkmn.push(new pokemon('zekrom', 'images/zekrom.png', 'cries/644 - Zekrom.wav'));
pkmn.push(new pokemon('groudon', 'images/groudon.png', 'cries/383 - Groudon.wav'));
pkmn.push(new pokemon('ampharos', 'images/ampharos.png', 'cries/181 - Ampharos.wav'));
pkmn.push(new pokemon('volcarona', 'images/volcarona.png', 'cries/637 - Volcarona.wav'));
pkmn.push(new pokemon('togepi', 'images/togepi.png', 'cries/175 - Togepi.wav'));
pkmn.push(new pokemon('entei', 'images/entei.png', 'cries/244 - Entei.wav'));
pkmn.push(new pokemon('raikou', 'images/raikou.png', 'cries/243 - Raikou.wav'));
pkmn.push(new pokemon('suicune', 'images/suicune.png', 'cries/245 - Suicune.wav'));
pkmn.push(new pokemon('pikachu', 'images/pikachu.png', 'cries/025 - Pikachu (01).wav'));
pkmn.push(new pokemon('mewtwo', 'images/mewtwo.png', 'cries/150 - Mewtwo.wav'));
pkmn.push(new pokemon('furret', 'images/furret.png', 'cries/162 - Furret.wav'));
pkmn.push(new pokemon('cradily', 'images/cradily.png', 'cries/346 - Cradily.wav'));
pkmn.push(new pokemon('lucario', 'images/lucario.png', 'cries/448 - Lucario.wav'));